from enum import Enum

class TRAININGREQUESTSTATUS(Enum):
    PENDING = "PENDING"
    VALIDATED ="VALIDATED"
    REFUSED = "REFUSED"

class PARTICIPATIONSTATUS(Enum):
    REGISTERED = "REGISTERED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABSENT = "ABSENT"
    CANCELLED = "CANCELLED"