from enum import Enum

class TRAININGREQUESTSTATUS(Enum):
    PENDING = "PENDING"
    VALIDATED ="VALIDATED"
    REFUSED = "REFUSED"

class PARTICIPATIONSTATUS(Enum):
    REGISTERED = "REGISTERED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABSENT = "ABSENT"
    CANCELLED = "CANCELLED"

class SKILLSTATUS(Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    MIXED = "MIXED"
    MANUALLY_VALIDATED = "MANUALLY_VALIDATED"

class SKILLSOURCETYPE(Enum):
    DIPLOMA = "DIPLOMA"
    CERTIFICATION = "CERTIFICATION"
    TRAINING = "TRAINING"
    VALIDATION = "VALIDATION"