"""added foreign key in skill -> domaine *correction*

Revision ID: 0d46476b5bf7
Revises: c210813c9c97
Create Date: 2026-06-21 11:42:26.722559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d46476b5bf7'
down_revision: Union[str, Sequence[str], None] = 'c210813c9c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
