"""make training request validator nullable and a desc field also nullable

Revision ID: 42e026fabcb5
Revises: a8c26db4a282
Create Date: 2026-06-13 23:52:18.398561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e026fabcb5'
down_revision: Union[str, Sequence[str], None] = 'a8c26db4a282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_request', sa.Column('desc', sa.String(length=50), nullable=True))
    op.alter_column('training_request', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('training_request', 'reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('training_request', 'requested_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('training_request', 'id_validator',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_request', 'id_validator',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_request', 'requested_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('training_request', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('training_request', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('training_request', 'desc')
    # ### end Alembic commands ###
