"""add is_deleted columns

Revision ID: 5f20697c991f
Revises: a225be9b262e
Create Date: 2026-06-11 12:05:05.752066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f20697c991f'
down_revision: Union[str, Sequence[str], None] = 'a225be9b262e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certification', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('certificationxskill', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('diploma', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('diplomaxskill', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('domaine', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('employee', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('employeexcertification', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('employeexdiploma', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('participation', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('provide', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('role', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('skill', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('skill_validation', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training_request', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training_source', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('trainingxskill', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('validation_type', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_type', 'is_deleted')
    op.drop_column('trainingxskill', 'is_deleted')
    op.drop_column('training_source', 'is_deleted')
    op.drop_column('training_request', 'is_deleted')
    op.drop_column('training', 'is_deleted')
    op.drop_column('skill_validation', 'is_deleted')
    op.drop_column('skill', 'is_deleted')
    op.drop_column('role', 'is_deleted')
    op.drop_column('provide', 'is_active')
    op.drop_column('participation', 'is_deleted')
    op.drop_column('employeexdiploma', 'is_deleted')
    op.drop_column('employeexcertification', 'is_deleted')
    op.drop_column('employee', 'is_deleted')
    op.drop_column('domaine', 'is_deleted')
    op.drop_column('diplomaxskill', 'is_deleted')
    op.drop_column('diploma', 'is_deleted')
    op.drop_column('certificationxskill', 'is_deleted')
    op.drop_column('certification', 'is_deleted')
    # ### end Alembic commands ###
