"""add access level

Revision ID: 668208169cc4
Revises: b8deb450dd72
Create Date: 2026-06-15 08:24:42.735502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668208169cc4'
down_revision: Union[str, Sequence[str], None] = 'b8deb450dd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'access_level',
        sa.Column('id_access_level', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=50), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id_access_level')
    )

    op.execute("""
        INSERT INTO access_level (id_access_level, label, level)
        VALUES
        (1, 'Employee', 1),
        (2, 'Manager', 2),
        (3, 'HR', 3)
    """)

    op.add_column(
        'role',
        sa.Column(
            'id_access_level',
            sa.Integer(),
            server_default='1',
            nullable=False
        )
    )

    op.create_foreign_key(
        None,
        'role',
        'access_level',
        ['id_access_level'],
        ['id_access_level']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'id_access_level')
    op.drop_table('access_level')
    # ### end Alembic commands ###
