"""added validity_month to certification_model

Revision ID: 89b15700ddd1
Revises: 9cd78bf5fcd3
Create Date: 2026-06-19 09:45:52.256441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b15700ddd1'
down_revision: Union[str, Sequence[str], None] = '9cd78bf5fcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certification', sa.Column('validity_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certification', 'validity_month')
    # ### end Alembic commands ###
