"""cleaning errors - certification and diploma

Revision ID: 9cd78bf5fcd3
Revises: fa6a0d003c4d
Create Date: 2026-06-18 15:53:39.302953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd78bf5fcd3'
down_revision: Union[str, Sequence[str], None] = 'fa6a0d003c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
