"""create initial schema

Revision ID: a8c26db4a282
Revises: 
Create Date: 2026-06-12 15:25:24.858886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c26db4a282'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domaine',
    sa.Column('id_domaine', sa.Integer(), nullable=False),
    sa.Column('nom_domaine', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_domaine')
    )
    op.create_table('role',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('denomination_role', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('skill',
    sa.Column('id_skill', sa.Integer(), nullable=False),
    sa.Column('name_skill', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_skill')
    )
    op.create_table('training_source',
    sa.Column('id_source', sa.Integer(), nullable=False),
    sa.Column('name_source', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_source')
    )
    op.create_table('validation_type',
    sa.Column('id_validation', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('denomination_validation', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_validation')
    )
    op.create_table('certification',
    sa.Column('id_certification', sa.Integer(), nullable=False),
    sa.Column('subject_certification', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id_domaine', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_domaine'], ['domaine.id_domaine'], ),
    sa.PrimaryKeyConstraint('id_certification')
    )
    op.create_table('diploma',
    sa.Column('id_diploma', sa.Integer(), nullable=False),
    sa.Column('subject_diploma', sa.String(length=50), nullable=True),
    sa.Column('level_diploma', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id_domaine', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_domaine'], ['domaine.id_domaine'], ),
    sa.PrimaryKeyConstraint('id_diploma')
    )
    op.create_table('employee',
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hash_password', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_manager', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_manager'], ['employee.id_employee'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_employee')
    )
    op.create_table('training',
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('id_domaine', sa.Integer(), nullable=True),
    sa.Column('start_', sa.Date(), nullable=True),
    sa.Column('end_', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_domaine'], ['domaine.id_domaine'], ),
    sa.PrimaryKeyConstraint('id_training')
    )
    op.create_table('certificationxskill',
    sa.Column('id_certification', sa.Integer(), nullable=False),
    sa.Column('id_skill', sa.Integer(), nullable=False),
    sa.Column('granted_level', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_certification'], ['certification.id_certification'], ),
    sa.ForeignKeyConstraint(['id_skill'], ['skill.id_skill'], ),
    sa.PrimaryKeyConstraint('id_certification', 'id_skill')
    )
    op.create_table('diplomaxskill',
    sa.Column('id_diploma', sa.Integer(), nullable=False),
    sa.Column('id_skill', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_diploma'], ['diploma.id_diploma'], ),
    sa.ForeignKeyConstraint(['id_skill'], ['skill.id_skill'], ),
    sa.PrimaryKeyConstraint('id_diploma', 'id_skill')
    )
    op.create_table('employeexcertification',
    sa.Column('id_employee_certification', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_certification', sa.Integer(), nullable=False),
    sa.Column('start_', sa.Date(), nullable=True),
    sa.Column('end_', sa.Date(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('organism', sa.String(length=50), nullable=True),
    sa.Column('evaluation', sa.String(length=50), nullable=True),
    sa.Column('doc', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_certification'], ['certification.id_certification'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.PrimaryKeyConstraint('id_employee_certification')
    )
    op.create_table('employeexdiploma',
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_diploma', sa.Integer(), nullable=False),
    sa.Column('end_', sa.Date(), nullable=True),
    sa.Column('school', sa.String(length=50), nullable=True),
    sa.Column('start_', sa.Date(), nullable=True),
    sa.Column('distinction', sa.String(length=50), nullable=True),
    sa.Column('doc', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_diploma'], ['diploma.id_diploma'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.PrimaryKeyConstraint('id_employee', 'id_diploma')
    )
    op.create_table('participation',
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.PrimaryKeyConstraint('id_employee', 'id_training')
    )
    op.create_table('provide',
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.Column('id_source', sa.Integer(), nullable=False),
    sa.Column('cost_hour', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['id_source'], ['training_source.id_source'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.PrimaryKeyConstraint('id_training', 'id_source')
    )
    op.create_table('skill_validation',
    sa.Column('id_skill_validation', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=True),
    sa.Column('level_skill', sa.Integer(), nullable=True),
    sa.Column('id_validation', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_validator', sa.Integer(), nullable=False),
    sa.Column('id_skill', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.ForeignKeyConstraint(['id_skill'], ['skill.id_skill'], ),
    sa.ForeignKeyConstraint(['id_validation'], ['validation_type.id_validation'], ),
    sa.ForeignKeyConstraint(['id_validator'], ['employee.id_employee'], ),
    sa.PrimaryKeyConstraint('id_skill_validation')
    )
    op.create_table('training_request',
    sa.Column('id_training_request', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_training', sa.Integer(), nullable=True),
    sa.Column('id_validator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id_employee'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.ForeignKeyConstraint(['id_validator'], ['employee.id_employee'], ),
    sa.PrimaryKeyConstraint('id_training_request')
    )
    op.create_table('trainingxcertification',
    sa.Column('id_certification', sa.Integer(), nullable=False),
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_certification'], ['certification.id_certification'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.PrimaryKeyConstraint('id_certification', 'id_training')
    )
    op.create_table('trainingxdiploma',
    sa.Column('id_diploma', sa.Integer(), nullable=False),
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_diploma'], ['diploma.id_diploma'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.PrimaryKeyConstraint('id_diploma', 'id_training')
    )
    op.create_table('trainingxskill',
    sa.Column('id_skill', sa.Integer(), nullable=False),
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.Column('granted_level', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_skill'], ['skill.id_skill'], ),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], ),
    sa.PrimaryKeyConstraint('id_skill', 'id_training')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingxskill')
    op.drop_table('trainingxdiploma')
    op.drop_table('trainingxcertification')
    op.drop_table('training_request')
    op.drop_table('skill_validation')
    op.drop_table('provide')
    op.drop_table('participation')
    op.drop_table('employeexdiploma')
    op.drop_table('employeexcertification')
    op.drop_table('diplomaxskill')
    op.drop_table('certificationxskill')
    op.drop_table('training')
    op.drop_table('employee')
    op.drop_table('diploma')
    op.drop_table('certification')
    op.drop_table('validation_type')
    op.drop_table('training_source')
    op.drop_table('skill')
    op.drop_table('role')
    op.drop_table('domaine')
    # ### end Alembic commands ###
