"""changed field desc to request_desc and it's size to 150

Revision ID: b8deb450dd72
Revises: 42e026fabcb5
Create Date: 2026-06-13 23:56:43.390177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8deb450dd72'
down_revision: Union[str, Sequence[str], None] = '42e026fabcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_request', sa.Column('request_desc', sa.String(length=150), nullable=True))
    op.drop_column('training_request', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_request', sa.Column('desc', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('training_request', 'request_desc')
    # ### end Alembic commands ###
