"""added foreign key in skill -> domaine

Revision ID: c210813c9c97
Revises: 89b15700ddd1
Create Date: 2026-06-21 11:24:35.410527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c210813c9c97'
down_revision: Union[str, Sequence[str], None] = '89b15700ddd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('id_domaine', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill', 'domaine', ['id_domaine'], ['id_domaine'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_column('skill', 'id_domaine')
    # ### end Alembic commands ###
