"""deleted provide model - changed the db

Revision ID: d32535c9a5d1
Revises: f6b39bd2fa69
Create Date: 2026-06-22 08:26:49.952275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32535c9a5d1'
down_revision: Union[str, Sequence[str], None] = 'f6b39bd2fa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provide')
    op.add_column('training', sa.Column('id_source', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('cost_hour', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('training', sa.Column('duration_hours', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'training', 'training_source', ['id_source'], ['id_source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'duration_hours')
    op.drop_column('training', 'cost_hour')
    op.drop_column('training', 'id_source')
    op.create_table('provide',
    sa.Column('id_training', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_source', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_hour', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_source'], ['training_source.id_source'], name=op.f('provide_id_source_fkey')),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], name=op.f('provide_id_training_fkey')),
    sa.PrimaryKeyConstraint('id_training', 'id_source', name=op.f('provide_pkey'))
    )
    # ### end Alembic commands ###
