"""add certification and diploma to training

Revision ID: fa6a0d003c4d
Revises: 668208169cc4
Create Date: 2026-06-18 15:34:53.175683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6a0d003c4d'
down_revision: Union[str, Sequence[str], None] = '668208169cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingxcertification')
    op.drop_table('trainingxdiploma')
    op.add_column('training', sa.Column('id_certification', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('id_diploma', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'certification', ['id_certification'], ['id_certification'])
    op.create_foreign_key(None, 'training', 'diploma', ['id_diploma'], ['id_diploma'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'id_diploma')
    op.drop_column('training', 'id_certification')
    op.create_table('trainingxdiploma',
    sa.Column('id_diploma', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_training', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_diploma'], ['diploma.id_diploma'], name=op.f('trainingxdiploma_id_diploma_fkey')),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], name=op.f('trainingxdiploma_id_training_fkey')),
    sa.PrimaryKeyConstraint('id_diploma', 'id_training', name=op.f('trainingxdiploma_pkey'))
    )
    op.create_table('trainingxcertification',
    sa.Column('id_certification', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_training', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_certification'], ['certification.id_certification'], name=op.f('trainingxcertification_id_certification_fkey')),
    sa.ForeignKeyConstraint(['id_training'], ['training.id_training'], name=op.f('trainingxcertification_id_training_fkey')),
    sa.PrimaryKeyConstraint('id_certification', 'id_training', name=op.f('trainingxcertification_pkey'))
    )
    # ### end Alembic commands ###
