-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.certification DROP CONSTRAINT IF EXISTS certification_id_domaine_fkey;

ALTER TABLE IF EXISTS public.certificationxskill DROP CONSTRAINT IF EXISTS certificationxskill_id_certification_fkey;

ALTER TABLE IF EXISTS public.certificationxskill DROP CONSTRAINT IF EXISTS certificationxskill_id_skill_fkey;

ALTER TABLE IF EXISTS public.diploma DROP CONSTRAINT IF EXISTS diploma_id_domaine_fkey;

ALTER TABLE IF EXISTS public.diplomaxskill DROP CONSTRAINT IF EXISTS diplomaxskill_id_diploma_fkey;

ALTER TABLE IF EXISTS public.diplomaxskill DROP CONSTRAINT IF EXISTS diplomaxskill_id_skill_fkey;

ALTER TABLE IF EXISTS public.employee DROP CONSTRAINT IF EXISTS employee_id_manager_fkey;

ALTER TABLE IF EXISTS public.employee DROP CONSTRAINT IF EXISTS employee_id_role_fkey;

ALTER TABLE IF EXISTS public.employeexcertification DROP CONSTRAINT IF EXISTS employeexcertification_id_certification_fkey;

ALTER TABLE IF EXISTS public.employeexcertification DROP CONSTRAINT IF EXISTS employeexcertification_id_employee_fkey;

ALTER TABLE IF EXISTS public.employeexdiploma DROP CONSTRAINT IF EXISTS employeexdiploma_id_diploma_fkey;

ALTER TABLE IF EXISTS public.employeexdiploma DROP CONSTRAINT IF EXISTS employeexdiploma_id_employee_fkey;

ALTER TABLE IF EXISTS public.participation DROP CONSTRAINT IF EXISTS participation_id_employee_fkey;

ALTER TABLE IF EXISTS public.participation DROP CONSTRAINT IF EXISTS participation_id_training_fkey;

ALTER TABLE IF EXISTS public.provide DROP CONSTRAINT IF EXISTS provide_id_source_fkey;

ALTER TABLE IF EXISTS public.provide DROP CONSTRAINT IF EXISTS provide_id_training_fkey;

ALTER TABLE IF EXISTS public.skill_validation DROP CONSTRAINT IF EXISTS skill_validation_id_employee_fkey;

ALTER TABLE IF EXISTS public.skill_validation DROP CONSTRAINT IF EXISTS skill_validation_id_skill_fkey;

ALTER TABLE IF EXISTS public.skill_validation DROP CONSTRAINT IF EXISTS skill_validation_id_validation_fkey;

ALTER TABLE IF EXISTS public.skill_validation DROP CONSTRAINT IF EXISTS skill_validation_id_validator_fkey;

ALTER TABLE IF EXISTS public.training DROP CONSTRAINT IF EXISTS training_id_domaine_fkey;

ALTER TABLE IF EXISTS public.training_request DROP CONSTRAINT IF EXISTS training_request_id_employee_fkey;

ALTER TABLE IF EXISTS public.training_request DROP CONSTRAINT IF EXISTS training_request_id_training_fkey;

ALTER TABLE IF EXISTS public.training_request DROP CONSTRAINT IF EXISTS training_request_id_validator_fkey;

ALTER TABLE IF EXISTS public.trainingxcertification DROP CONSTRAINT IF EXISTS trainingxcertification_id_certification_fkey;

ALTER TABLE IF EXISTS public.trainingxcertification DROP CONSTRAINT IF EXISTS trainingxcertification_id_training_fkey;

ALTER TABLE IF EXISTS public.trainingxdiploma DROP CONSTRAINT IF EXISTS trainingxdiploma_id_diploma_fkey;

ALTER TABLE IF EXISTS public.trainingxdiploma DROP CONSTRAINT IF EXISTS trainingxdiploma_id_training_fkey;

ALTER TABLE IF EXISTS public.trainingxskill DROP CONSTRAINT IF EXISTS trainingxskill_id_skill_fkey;

ALTER TABLE IF EXISTS public.trainingxskill DROP CONSTRAINT IF EXISTS trainingxskill_id_training_fkey;



DROP TABLE IF EXISTS public.certification;

CREATE TABLE IF NOT EXISTS public.certification
(
    id_certification serial NOT NULL,
    subject_certification character varying(50) COLLATE pg_catalog."default",
    id_domaine integer NOT NULL,
    CONSTRAINT certification_pkey PRIMARY KEY (id_certification)
);

DROP TABLE IF EXISTS public.certificationxskill;

CREATE TABLE IF NOT EXISTS public.certificationxskill
(
    id_certification integer NOT NULL,
    id_skill integer NOT NULL,
    granted_level integer,
    CONSTRAINT certificationxskill_pkey PRIMARY KEY (id_certification, id_skill)
);

DROP TABLE IF EXISTS public.diploma;

CREATE TABLE IF NOT EXISTS public.diploma
(
    id_diploma serial NOT NULL,
    subject_diploma character varying(50) COLLATE pg_catalog."default",
    level_diploma character varying(50) COLLATE pg_catalog."default",
    id_domaine integer NOT NULL,
    CONSTRAINT diploma_pkey PRIMARY KEY (id_diploma)
);

DROP TABLE IF EXISTS public.diplomaxskill;

CREATE TABLE IF NOT EXISTS public.diplomaxskill
(
    id_diploma integer NOT NULL,
    id_skill integer NOT NULL,
    min_level integer,
    CONSTRAINT diplomaxskill_pkey PRIMARY KEY (id_diploma, id_skill)
);

DROP TABLE IF EXISTS public.domaine;

CREATE TABLE IF NOT EXISTS public.domaine
(
    id_domaine serial NOT NULL,
    nom_domaine character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT domaine_pkey PRIMARY KEY (id_domaine)
);

DROP TABLE IF EXISTS public.employee;

CREATE TABLE IF NOT EXISTS public.employee
(
    id_employee serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    hash_password character varying(50) COLLATE pg_catalog."default",
    mail character varying(50) COLLATE pg_catalog."default",
    id_role integer NOT NULL,
    id_manager integer,
    CONSTRAINT employee_pkey PRIMARY KEY (id_employee)
);

DROP TABLE IF EXISTS public.employeexcertification;

CREATE TABLE IF NOT EXISTS public.employeexcertification
(
    id_employee integer NOT NULL,
    id_certification integer NOT NULL,
    start_ date,
    end_ date,
    expiration date,
    organism character varying(50) COLLATE pg_catalog."default",
    evaluation character varying(50) COLLATE pg_catalog."default",
    doc character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT employeexcertification_pkey PRIMARY KEY (id_employee, id_certification)
);

DROP TABLE IF EXISTS public.employeexdiploma;

CREATE TABLE IF NOT EXISTS public.employeexdiploma
(
    id_employee integer NOT NULL,
    id_diploma integer NOT NULL,
    end_ date,
    school character varying(50) COLLATE pg_catalog."default",
    start_ date,
    distinction character varying(50) COLLATE pg_catalog."default",
    doc character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT employeexdiploma_pkey PRIMARY KEY (id_employee, id_diploma)
);

DROP TABLE IF EXISTS public.participation;

CREATE TABLE IF NOT EXISTS public.participation
(
    id_employee integer NOT NULL,
    id_training integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT participation_pkey PRIMARY KEY (id_employee, id_training)
);

DROP TABLE IF EXISTS public.provide;

CREATE TABLE IF NOT EXISTS public.provide
(
    id_training integer NOT NULL,
    id_source integer NOT NULL,
    cost_hour numeric(15, 2),
    duration_hours numeric(15, 2),
    CONSTRAINT provide_pkey PRIMARY KEY (id_training, id_source)
);

DROP TABLE IF EXISTS public.role;

CREATE TABLE IF NOT EXISTS public.role
(
    id_role serial NOT NULL,
    denomination_role character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id_role)
);

DROP TABLE IF EXISTS public.skill;

CREATE TABLE IF NOT EXISTS public.skill
(
    id_skill serial NOT NULL,
    name_skill character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT skill_pkey PRIMARY KEY (id_skill)
);

DROP TABLE IF EXISTS public.skill_validation;

CREATE TABLE IF NOT EXISTS public.skill_validation
(
    id_skill_validation serial NOT NULL,
    date_ date,
    level_skill integer,
    id_validation integer NOT NULL,
    id_employee integer NOT NULL,
    id_validator integer NOT NULL,
    id_skill integer NOT NULL,
    CONSTRAINT skill_validation_pkey PRIMARY KEY (id_skill_validation)
);

DROP TABLE IF EXISTS public.training;

CREATE TABLE IF NOT EXISTS public.training
(
    id_training serial NOT NULL,
    title character varying(50) COLLATE pg_catalog."default",
    id_domaine integer,
    start_ date,
    end_ date,
    CONSTRAINT training_pkey PRIMARY KEY (id_training)
);

DROP TABLE IF EXISTS public.training_request;

CREATE TABLE IF NOT EXISTS public.training_request
(
    id_training_request serial NOT NULL,
    status character varying(50) COLLATE pg_catalog."default",
    reason character varying(50) COLLATE pg_catalog."default",
    requested_at date,
    id_employee integer NOT NULL,
    id_training integer,
    id_validator integer NOT NULL,
    CONSTRAINT training_request_pkey PRIMARY KEY (id_training_request)
);

DROP TABLE IF EXISTS public.training_source;

CREATE TABLE IF NOT EXISTS public.training_source
(
    id_source serial NOT NULL,
    name_source character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT training_source_pkey PRIMARY KEY (id_source)
);

DROP TABLE IF EXISTS public.trainingxcertification;

CREATE TABLE IF NOT EXISTS public.trainingxcertification
(
    id_certification integer NOT NULL,
    id_training integer NOT NULL,
    CONSTRAINT trainingxcertification_pkey PRIMARY KEY (id_certification, id_training)
);

DROP TABLE IF EXISTS public.trainingxdiploma;

CREATE TABLE IF NOT EXISTS public.trainingxdiploma
(
    id_diploma integer NOT NULL,
    id_training integer NOT NULL,
    CONSTRAINT trainingxdiploma_pkey PRIMARY KEY (id_diploma, id_training)
);

DROP TABLE IF EXISTS public.trainingxskill;

CREATE TABLE IF NOT EXISTS public.trainingxskill
(
    id_skill integer NOT NULL,
    id_training integer NOT NULL,
    granted_level integer,
    CONSTRAINT trainingxskill_pkey PRIMARY KEY (id_skill, id_training)
);

DROP TABLE IF EXISTS public.validation_type;

CREATE TABLE IF NOT EXISTS public.validation_type
(
    id_validation serial NOT NULL,
    source character varying(50) COLLATE pg_catalog."default",
    denomination_validation character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT validation_type_pkey PRIMARY KEY (id_validation)
);

ALTER TABLE IF EXISTS public.certification
    ADD CONSTRAINT certification_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certificationxskill
    ADD CONSTRAINT certificationxskill_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certificationxskill
    ADD CONSTRAINT certificationxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diploma
    ADD CONSTRAINT diploma_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diplomaxskill
    ADD CONSTRAINT diplomaxskill_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diplomaxskill
    ADD CONSTRAINT diplomaxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_id_manager_fkey FOREIGN KEY (id_manager)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_id_role_fkey FOREIGN KEY (id_role)
    REFERENCES public.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexcertification
    ADD CONSTRAINT employeexcertification_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexcertification
    ADD CONSTRAINT employeexcertification_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexdiploma
    ADD CONSTRAINT employeexdiploma_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexdiploma
    ADD CONSTRAINT employeexdiploma_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provide
    ADD CONSTRAINT provide_id_source_fkey FOREIGN KEY (id_source)
    REFERENCES public.training_source (id_source) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provide
    ADD CONSTRAINT provide_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_validation_fkey FOREIGN KEY (id_validation)
    REFERENCES public.validation_type (id_validation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_validator_fkey FOREIGN KEY (id_validator)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training
    ADD CONSTRAINT training_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_validator_fkey FOREIGN KEY (id_validator)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxcertification
    ADD CONSTRAINT trainingxcertification_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxcertification
    ADD CONSTRAINT trainingxcertification_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxdiploma
    ADD CONSTRAINT trainingxdiploma_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxdiploma
    ADD CONSTRAINT trainingxdiploma_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxskill
    ADD CONSTRAINT trainingxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxskill
    ADD CONSTRAINT trainingxskill_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;